feat: Add new Pathfinder 2e Creature layout (#436)
javalent/fantasy-statblocks pull request #438
Opened 2024-07-13 18:03 UTC by miscoined

## Pull Request Description

Add a new default Pathfinder 2e Creature layout. See #436 for rationale and background. This adds this as a new layout, without replacing the existing Basic layout. I'm opening this as a draft PR for now until I finish adding documentation and layout restoration functionality - I thought early feedback would be useful in this case.

## Changes Proposed

- [x] Add a new Pathfinder 2e Creature Layout
- [x] Update Pathfinder 2e CSS from the upstream repo
- [ ] Add documentation for the new layout
- [ ] Add/update the default layout block for layout restoration functionality

## Related Issues

Progresses #436.

## Checklist (WIP)

- [x] I have read the contribution guidelines and code of conduct.
- [ ] I have tested the changes locally and they are working as expected.
- [ ] I have added appropriate comments and documentation for the code changes.
- [x] My code follows the coding style and standards of this project.
- [x] I have rebased my branch on the latest main (or master) branch.
- [ ] All tests (if applicable) have passed successfully.
- [ ] I have run linters and fixed any issues.
- [x] I have checked for any potential security issues or vulnerabilities.

## Screenshots (if applicable)

Will add later, before flipping this out of a draft PR

2024-08-10 00:14 UTC, valentine195 commented
Hey @miscoined, this looks great. Is this meant to slot into existing PF2e creature stat blocks used by the TTRPG share?

2024-08-10 00:22 UTC, valentine195 requested changes

2024-08-10 00:22 UTC, valentine195 commented on src/settings/layout/blocks/ui/block.ts
> +            .setName("Do Not Add Property as CSS Class")
I usually try to prefer making these things _perform_ the task rather than turning it off. Could you please refactor this setting to that?

2024-08-10 00:22 UTC, valentine195 commented on src/layouts/pathfinder 2e/pf2e.ts
> +                            condition: "return plugin.app.plugins.enabledPlugins.has(\"initiative-tracker\");\n"
This is actually genius! Very clever.

2024-08-10 00:22 UTC, valentine195 commented on src/layouts/pathfinder 2e/pf2e.ts
> +                    callback: "var s = property.bonus < 0 ? \"-\" : \"+\";\ns += Math.abs(property.bonus);\nif (property.desc) {\n  s += \" \" + property.desc\n}\nif (property.damage) {\n  s += \", _
This will return `NaN` if `property.bonus` is undefined

2024-08-10 00:23 UTC, valentine195 commented
Sorry I let this sit for so long; been a very busy summer. I appreciate the work you have been doing.

2025-02-10 03:14 UTC, miscoined commented on src/settings/layout/blocks/ui/block.ts
> +            .setName("Do Not Add Property as CSS Class")
I did that for consistency with the same option for other blocks. I'm happy to change it if you'd prefer the inconsistency. I'd also be happy to change the other options as well (I'd probably do it in a separate PR), but I'm not sure if that would mean that existing user's settings would actually end up inverted. Just checking what you'd prefer :)

2025-02-10 03:33 UTC, miscoined commented on src/layouts/pathfinder 2e/pf2e.ts
> +                    callback: "var s = property.bonus < 0 ? \"-\" : \"+\";\ns += Math.abs(property.bonus);\nif (property.desc) {\n  s += \" \" + property.desc\n}\nif (property.damage) {\n  s += \", _
Done

2025-02-10 03:37 UTC, miscoined commented
Hey! I had a busy while myself so I'm sorry it took so long to get back to this. I've fixed up any merge conflicts, updated the documentation, and made the changes you requested. I've been using this on my own personal vault for a while now and haven't noticed any problems.

2025-02-10 13:55 UTC, merged

2025-02-10 13:56 UTC, valentine195 commented
I added you to the repo but you are under no obligation to do anything :) I just had a kid so I’ve been out of commission for awhile.

2025-02-10 14:29 UTC, miscoined commented
> I added you to the repo but you are under no obligation to do anything :) I just had a kid so I’ve been out of commission for awhile.

Thank you for the quick merge and the add! and congrats on the new kid :D